hydra:
  run:
    dir: hydra_output/

exp:
  exp_name: test
  api_key: LSTIie51umcysQtnef1Zzil6V
  project_name: secondhand-apartment-price-forecasting
  model: lgb
  use_pickle: False

data:
  seed: 42
  n_splits: 5
  vec_max_features: 60000
  vec_n_components: 200

lgb:
  num_iterations: 100000
  objective: regression
  metric: rmse
  boosting: gbdt
  early_stopping_round: 500
  learning_rate: 0.005
  first_metric_only: True
  feature_fraction: 0.8
  bagging_fraction: 0.7
  bagging_freq: 1

cat:
  eval_metric: RMSE
  loss_function: RMSE
  iterations: 30000
  verbose: 1000
  early_stopping_rounds: 500
  task_type: GPU
