hydra:
  run:
    dir: hydra_output/

exp:
  exp_name: test
  api_key: LSTIie51umcysQtnef1Zzil6V
  project_name: secondhand-apartment-price-forecasting
  model: lgb
  use_pickle: False

data:
  seed: 42
  n_splits: 5
  sampling: 0.5
  vec_max_features: 60000
  vec_n_components: 200

lgb:
  num_iterations: 100000
  objective: regression
  metric: mae
  boosting: gbdt
  early_stopping_round: 1000
  learning_rate: 0.01
  first_metric_only: True
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 1

cat:
  eval_metric: MAE
  loss_function: MAE
  iterations: 30000
  verbose: 1000
  early_stopping_rounds: 500
  task_type: GPU
